"""init

Revision ID: 2e8e603859e2
Revises: 
Create Date: 2019-06-09 14:10:35.792370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e8e603859e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group', sa.Unicode(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_group', sa.Integer(), nullable=True),
    sa.Column('name', sa.Unicode(length=30), nullable=True),
    sa.Column('surname', sa.Unicode(length=30), nullable=True),
    sa.Column('patronymic', sa.Unicode(length=30), nullable=True),
    sa.ForeignKeyConstraint(['id_group'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('group')
    # ### end Alembic commands ###
